DROP TABLE IF EXISTS target;
DROP TYPE IF EXISTS target_des;

CREATE TABLE target (
  id SERIAL PRIMARY KEY,
  month INTEGER NOT NULL,
  week INTEGER NOT NULL,
  sub1 DOUBLE PRECISION NOT NULL DEFAULT 0,
  sub2 DOUBLE PRECISION NOT NULL DEFAULT 0
);
